[Pretrained Word2Vec Embeddings](#Pretrained-Word2Vec-Embeddings)   

1. [Google News Embedding](#Google-News-Embedding)    
2. [Similarity Scores](#Similarity-Scores)    
3. [Debunking Some Common Examples](#Debunking-Some-Common-Examples)
4. [Other Pretrained Models](Other-Pretrained-Models)
5. [Building Your Own Model](Building-Your-Own-Model)

Note: [Gensim Word2Vec Tutorial](https://www.kaggle.com/code/pierremegret/gensim-word2vec-tutorial/notebook)


# Pretrained Word2Vec Embeddings

Now that we have a better feel for the model behind Word2Vec we'll see how we can implement word embeddings developed by teams with more computational resources than most everyone has at home.

We'll be using `gensim` and more or less working through the tutorial in their documentation here https://radimrehurek.com/gensim/auto_examples/tutorials/run_word2vec.html. I'll also try my best to pull in some examples from Mikolov et. al.'s original papers.

First things first, please try running the following code.

In [1]:
import numpy as np

In [2]:
import gensim.downloader as api

In [3]:
wv = api.load('word2vec-google-news-300')

[=================================================-] 100.0% 1662.7/1662.8MB downloaded


The above code takes a bit to run, and takes a long while to run if it's your first time running it (the model is approximately 2GB). So please hit shift + enter now while I'm talking so it will load in time for our first coding break.

## Google News Embedding
The model we just loaded using gensim was built by Google using their Google News dataset. Their network was trained with a vocabulary of 3 million words and phrases using.

These 3 million dimensional one hot encoded vectors were then projected down to 300 features, meaning that each word vector in the embedding has 300 dimensions. Using the language from `Last week's class` their $M = 3,000,000$ and their #N= 300#.

### Accessing the Word Vectors
Once the above has loaded you can access the embedding of any word or phrase in the embedding by simply calling wv[string]. Let's see

In [4]:
wv['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [5]:
wv['woman']

array([ 2.43164062e-01, -7.71484375e-02, -1.03027344e-01, -1.07421875e-01,
        1.18164062e-01, -1.07421875e-01, -1.14257812e-01,  2.56347656e-02,
        1.11816406e-01,  4.85839844e-02, -9.71679688e-02, -3.43750000e-01,
       -6.29882812e-02, -1.25000000e-01, -2.70996094e-02,  9.42382812e-02,
       -1.87500000e-01, -5.34667969e-02,  6.25000000e-02, -3.05175781e-02,
       -2.90527344e-02, -4.80957031e-02, -5.51757812e-02, -4.08203125e-01,
        1.01318359e-02, -2.32421875e-01, -1.70898438e-01,  2.63671875e-01,
        3.49609375e-01, -2.11914062e-01,  1.43554688e-01, -6.22558594e-03,
       -2.25585938e-01, -1.05468750e-01, -1.16210938e-01,  1.23046875e-01,
        3.06640625e-01, -4.88281250e-02, -9.57031250e-02,  1.99218750e-01,
       -1.57226562e-01, -2.80761719e-02,  1.58203125e-01, -2.42919922e-02,
        1.29882812e-01, -8.98437500e-02, -7.61718750e-02,  3.54003906e-02,
       -3.06396484e-02,  1.52343750e-01,  5.24902344e-02,  1.60980225e-03,
        5.56640625e-02,  

In [6]:
wv['influenza']

array([ 6.29882812e-02,  1.49536133e-03,  9.61914062e-02,  1.71875000e-01,
        3.44238281e-02, -6.29882812e-02, -3.51562500e-01, -1.48437500e-01,
        2.39257812e-01, -1.12304688e-01,  1.14257812e-01, -4.94140625e-01,
        9.61914062e-02,  8.78906250e-02, -2.28515625e-01,  1.94335938e-01,
        1.31835938e-01,  3.73046875e-01,  2.57812500e-01,  2.43164062e-01,
       -3.43322754e-03, -3.04687500e-01,  2.71484375e-01, -1.41601562e-01,
        3.01513672e-02, -2.83203125e-02,  1.57226562e-01, -3.24218750e-01,
        1.62353516e-02,  5.78613281e-02, -2.03125000e-01, -1.71875000e-01,
        3.82812500e-01, -2.45117188e-01,  8.05664062e-02,  3.51562500e-02,
       -2.65625000e-01,  2.07031250e-01, -1.04370117e-02,  8.16406250e-01,
        1.26953125e-01, -9.81445312e-02, -1.40625000e-01,  1.29882812e-01,
        7.08007812e-02, -2.40234375e-01,  2.43164062e-01,  9.17968750e-02,
       -1.74804688e-01,  4.15039062e-03, -5.49316406e-02, -1.30859375e-01,
       -3.41796875e-01,  

### Retrieving the index
It would be nice to know whether or not a word/phrase we're interested in is in the vocabulary. We can check by looking at the word index for the vocabulary.



In [9]:
# index2word contains every word in the 
# vocabulary

# let's look at the first 20
for i in range(20):
    print(wv.index_to_key[i])

</s>
in
for
that
is
on
##
The
with
said
was
the
at
not
as
it
be
from
by
are


In [10]:
# wv.index2word is a list of the words/phrases in the vocab
print(wv.index_to_key[:20])

['</s>', 'in', 'for', 'that', 'is', 'on', '##', 'The', 'with', 'said', 'was', 'the', 'at', 'not', 'as', 'it', 'be', 'from', 'by', 'are']


## Similarity Scores
Similar to LSA Word2Vec can be used to find words that are similar to one another, which is useful for tasks like searching through a document for words related to a particular topic.

Work through the following to learn how to use the pretrained Word2Vec to find both the similarity between pairs of words, as well as find the most similar words to a predefined set.

### Calculating Similarities between pairs of word embeddings
There are a few different ways you can calculate similarity scores between pairs of vectors. You'll work through them now.

In [11]:
### similarity(word1, word2)
## call wv.similarity for two words/phrases
## Try and find the similarity between "apple" and
## other fruits and vegetables you know
print("apple and orange",wv.similarity("apple","orange"))
print("apple and tomato",wv.similarity("apple","tomato"))

apple and orange 0.39203462
apple and tomato 0.5608182


In [12]:
### cosine_similairties(vec1, array_of_vectors)
## call wv.cosine_similarities for a vector and a collection of vectors
## Create a numpy array where each row has the word embeddings 
## for the fruits and vegetables you were interested in
## compare to the word embedding for "apple"
embeddings = np.zeros((4,300))

embeddings[0,:] = wv['tomato']
embeddings[1,:] = wv['banana']
embeddings[2,:] = wv['orange']
embeddings[3,:] = wv['pear']

wv.cosine_similarities(wv['apple'], embeddings)

array([0.56081817, 0.5318406 , 0.3920346 , 0.64506968])

### Finding the most similar words
Another problem you may be interested in is finding the words that are most similar to a given word or vector.

In [13]:
print(wv.doesnt_match(["apple","banana","grapes","pear","jeans"]))

jeans


### One of these things just doesn't belong
Another fun feature is that you can put in a list of words and Word2Vec can pick out the one that doesn't belong.

In [ ]:
print(wv.doesnt_match(["apple","banana","grapes","pear","jeans"]))

## Debunking Some Common Examples
If you've ever heard of Word2Vec prior to this, you may have seen amazingly intuitive results like "King" - "Man" + "Woman" = "Queen".

While such examples are certainly eye-catching let's see how they hold up in actuality. Note inspiration for this section comes from this blog post https://blog.esciencecenter.nl/king-man-woman-king-9a7fd2935a85.

Use what you've learned above to test out the following "equations":

* king - man + woman = queen
* bigger - big + cold = colder
* Einstein - scientist + Picasso = painter
* Paris - France + Italy = Rome
* lebron - cavs + lakers = kobe

In [14]:
vector = wv['king'] - wv['man'] + wv['woman']
wv.similar_by_vector(vector)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [15]:
vector = wv['bigger'] - wv['big'] + wv['cold']
wv.similar_by_vector(vector)

[('cold', 0.7878133654594421),
 ('colder', 0.7053806185722351),
 ('warmer', 0.6308302283287048),
 ('colder_temperatures', 0.5584955215454102),
 ('cooler', 0.5487411022186279),
 ('chillier', 0.5474385619163513),
 ('chilly', 0.5405797958374023),
 ('Cold', 0.5328137874603271),
 ('frigid', 0.5286216735839844),
 ('snowier_winter', 0.5251795649528503)]

In [16]:
vector = wv['Paris'] - wv['France'] + wv['Italy']
wv.similar_by_vector(vector)

[('Milan', 0.7251641750335693),
 ('Rome', 0.7073156237602234),
 ('Italy', 0.6847635507583618),
 ('Paris', 0.6693719625473022),
 ('Palermo_Sicily', 0.6014109253883362),
 ('Italian', 0.596384584903717),
 ('Tuscany', 0.5672276020050049),
 ('Sicily', 0.5654013752937317),
 ('Bologna', 0.5645887851715088),
 ('Bologna_Italy', 0.5513801574707031)]

In [17]:
vector = wv['lebron'] - wv['cavs'] + wv['lakers']
wv.similar_by_vector(vector)

[('lakers', 0.8796191811561584),
 ('lebron', 0.7018214464187622),
 ('laker', 0.612667441368103),
 ('celtics', 0.6117448210716248),
 ('shaq', 0.5856783986091614),
 ('kobe', 0.5744044780731201),
 ('gasol', 0.5545269846916199),
 ('bynum', 0.543467104434967),
 ('nba', 0.5254707336425781),
 ('mavs', 0.517430305480957)]

## Other Pretrained Models
While we've looked at the Google News embedding there are a number of other pretrained Word2Vec embeddings that may be of interest.

This Github repository has a nice list of the pretrained models you can get online, https://github.com/3Top/word2vec-api#where-to-get-a-pretrained-models.

Here are the names from the gensim documentation.

In [18]:
# ['fasttext-wiki-news-subwords-300',
#  'conceptnet-numberbatch-17-06-300',
#  'word2vec-ruscorpora-300',
#  'word2vec-google-news-300',
#  'glove-wiki-gigaword-50',
#  'glove-wiki-gigaword-100',
#  'glove-wiki-gigaword-200',
#  'glove-wiki-gigaword-300',
#  'glove-twitter-25',
#  'glove-twitter-50',
#  'glove-twitter-100',
#  'glove-twitter-200',
#  '__testing_word2vec-matrix-synopsis']

## Building Your Own Model
`gensim` also offers the functionality to build your own Word2Vec model if you clean the data up. Let's demonstrate the process with a truly controversial example using Green Eggs and Ham by Dr. Seuss.

In [19]:
## Here is the text of Green Eggs and Ham
seuss = '''
"I AM SAM. I AM SAM. SAM I AM.

THAT SAM-I-AM! THAT SAM-I-AM! I DO NOT LIKE THAT SAM-I-AM!

DO WOULD YOU LIKE GREEN EGGS AND HAM?

I DO NOT LIKE THEM,SAM-I-AM.
I DO NOT LIKE GREEN EGGS AND HAM.

WOULD YOU LIKE THEM HERE OR THERE?

I WOULD NOT LIKE THEM HERE OR THERE.
I WOULD NOT LIKE THEM ANYWHERE.
I DO NOT LIKE GREEN EGGS AND HAM.
I DO NOT LIKE THEM, SAM-I-AM.

WOULD YOU LIKE THEM IN A HOUSE?
WOULD YOU LIKE THEN WITH A MOUSE?

I DO NOT LIKE THEM IN A HOUSE.
I DO NOT LIKE THEM WITH A MOUSE.
I DO NOT LIKE THEM HERE OR THERE.
I DO NOT LIKE THEM ANYWHERE.
I DO NOT LIKE GREEN EGGS AND HAM.
I DO NOT LIKE THEM, SAM-I-AM.

WOULD YOU EAT THEM IN A BOX?
WOULD YOU EAT THEM WITH A FOX?

NOT IN A BOX. NOT WITH A FOX.
NOT IN A HOUSE. NOT WITH A MOUSE.
I WOULD NOT EAT THEM HERE OR THERE.
I WOULD NOT EAT THEM ANYWHERE.
I WOULD NOT EAT GREEN EGGS AND HAM.
I DO NOT LIKE THEM, SAM-I-AM.

WOULD YOU? COULD YOU? IN A CAR?
EAT THEM! EAT THEM! HERE THEY ARE.

I WOULD NOT, COULD NOT, IN A CAR.

YOU MAY LIKE THEM. YOU WILL SEE.
YOU MAY LIKE THEM IN A TREE!

I WOULD NOT, COULD NOT IN A TREE.
NOT IN A CAR! YOU LET ME BE.
I DO NOT LIKE THEM IN A BOX.
I DO NOT LIKE THEM WITH A FOX.
I DO NOT LIKE THEM IN A HOUSE.
I DO NOT LIKE THEM WITH A MOUSE.
I DO NOT LIKE THEM HERE OR THERE.
I DO NOT LIKE THEM ANYWHERE.
I DO NOT LIKE GREEN EGGS AND HAM.
I DO NOT LIKE THEM, SAM-I-AM.

A TRAIN! A TRAIN! A TRAIN! A TRAIN!
COULD YOU, WOULD YOU ON A TRAIN?

NOT ON TRAIN! NOT IN A TREE!
NOT IN A CAR! SAM! LET ME BE!
I WOULD NOT, COULD NOT, IN A BOX.
I WOULD NOT, COULD NOT, WITH A FOX.
I WILL NOT EAT THEM IN A HOUSE.
I WILL NOT EAT THEM HERE OR THERE.
I WILL NOT EAT THEM ANYWHERE.
I DO NOT EAT GREEM EGGS AND HAM.
I DO NOT LIKE THEM, SAM-I-AM.

SAY! IN THE DARK? HERE IN THE DARK!
WOULD YOU, COULD YOU, IN THE DARK?

I WOULD NOT, COULD NOT, IN THE DARK.

WOULD YOU COULD YOU IN THE RAIN?

I WOULD NOT, COULD NOT IN THE RAIN.
NOT IN THE DARK. NOT ON A TRAIN.
NOT IN A CAR. NOT IN A TREE.
I DO NOT LIKE THEM, SAM, YOU SEE.
NOT IN A HOUSE. NOT IN A BOX.
NOT WITH A MOUSE. NOT WITH A FOX.
I WILL NOT EAT THEM HERE OR THERE.
I DO NOT LIKE THEM ANYWHERE!

YOU DO NOT LIKE GREEN EGGS AND HAM?

I DO NOT LIKE THEM, SAM-I-AM.

COULD YOU, WOULD YOU, WITH A GOAT?

I WOULD NOT, COULD NOT WITH A GOAT!

WOULD YOU, COULD YOU, ON A BOAT?

I COULD NOT, WOULD NOT, ON A BOAT.
I WILL NOT, WILL NOT, WITH A GOAT.
I WILL NOT EAT THEM IN THE RAIN.
NOT IN THE DARK! NOT IN A TREE!
NOT IN A CAR! YOU LET ME BE!
I DO NOT LIKE THEM IN A BOX.
I DO NOT LIKE THEM WITH A FOX.
I WILL NOT EAT THEM IN A HOUSE.
I DO NOT LIKE THEM WITH A MOUSE.
I DO NOT LIKE THEM HERE OR THERE.
I DO NOT LIKE THEM ANYWHERE!
I DO NOT LIKE GREEN EGGS AND HAM!
I DO NOT LIKE THEM, SAM-I-AM.

YOU DO NOT LIKE THEM. SO YOU SAY.
TRY THEM! TRY THEM! AND YOU MAY.
TRY THEM AND YOU MAY, I SAY.

sAM! IF YOU LET ME BE,
I WILL TRY THEM. YOU WILL SEE.

(... and he tries them ...)

SAY! I LIKE GREEN EGGS AND HAM!
I DO! I LIKE THEM, SAM-I-AM!
AND I WOULD EAT THEM IN A BOAT.
AND I WOULD EAT THEM WITH A GOAT...
AND I WILL EAT THEM, IN THE RAIN.
AND IN THE DARK. AND ON A TRAIN.
AND IN A CAR. AND IN A TREE.
THEY ARE SO GOOD, SO GOOD, YOU SEE!
SO I WILL EAT THEM IN A BOX.
AND I WILL EAT THEM WITH A FOX.
AND I WILL EAT THEM IN A HOUSE.
AND I WILL EAT THEM WITH A MOUSE.
AND I WILL EAT THEM HERE AND THERE.
SAY! I WILL EAT THEM ANYWHERE!
I DO SO LIKE GREEN EGGS AND HAM!
THANK YOU! THANK YOU, SAM I AM.
'''

In [20]:
# Here I clean it up a bit
seuss = seuss.replace("\n","").replace(","," ").replace('"',"").replace("(","").replace(")","")
seuss = seuss.replace(".",". ").replace("!","! ").replace("?","? ")

In [21]:
# The clean version
print(seuss)

I AM SAM.  I AM SAM.  SAM I AM. THAT SAM-I-AM!  THAT SAM-I-AM!  I DO NOT LIKE THAT SAM-I-AM! DO WOULD YOU LIKE GREEN EGGS AND HAM? I DO NOT LIKE THEM SAM-I-AM. I DO NOT LIKE GREEN EGGS AND HAM. WOULD YOU LIKE THEM HERE OR THERE? I WOULD NOT LIKE THEM HERE OR THERE. I WOULD NOT LIKE THEM ANYWHERE. I DO NOT LIKE GREEN EGGS AND HAM. I DO NOT LIKE THEM  SAM-I-AM. WOULD YOU LIKE THEM IN A HOUSE? WOULD YOU LIKE THEN WITH A MOUSE? I DO NOT LIKE THEM IN A HOUSE. I DO NOT LIKE THEM WITH A MOUSE. I DO NOT LIKE THEM HERE OR THERE. I DO NOT LIKE THEM ANYWHERE. I DO NOT LIKE GREEN EGGS AND HAM. I DO NOT LIKE THEM  SAM-I-AM. WOULD YOU EAT THEM IN A BOX? WOULD YOU EAT THEM WITH A FOX? NOT IN A BOX.  NOT WITH A FOX. NOT IN A HOUSE.  NOT WITH A MOUSE. I WOULD NOT EAT THEM HERE OR THERE. I WOULD NOT EAT THEM ANYWHERE. I WOULD NOT EAT GREEN EGGS AND HAM. I DO NOT LIKE THEM  SAM-I-AM. WOULD YOU?  COULD YOU?  IN A CAR? EAT THEM!  EAT THEM!  HERE THEY ARE. I WOULD NOT  COULD NOT  IN A CAR. YOU MAY LIKE THEM

In [22]:
# gensim only requires sequences of words in a sentence
from nltk.tokenize import sent_tokenize
from nltk import word_tokenize

In [23]:
# let's give them just that
sentences = [word_tokenize(sent) for sent in sent_tokenize(seuss)]

In [26]:
# You train a Word2Vec model in gensim with
# Word2Vec
from gensim.models import Word2Vec

In [30]:
import multiprocessing

cores = multiprocessing.cpu_count() # Count the number of cores in a computer

### Parameters

* `min_count` = int - Ignores all words with total absolute frequency lower than this - (2, 100)
* `window` = int - The maximum distance between the current and predicted word within a sentence. E.g. window words on the left and window words on the left of our target - (2, 10)
* `size` = int - Dimensionality of the feature vectors. - (50, 300)
* `sample` = float - The threshold for configuring which higher-frequency words are randomly downsampled. Highly influencial. - (0, 1e-5)
* `alpha` = float - The initial learning rate - (0.01, 0.05)
* `min_alpha` = float - Learning rate will linearly drop to min_alpha as training progresses. To set it: alpha - (min_alpha * epochs) ~ 0.00
* `negative` = int - If > 0, negative sampling will be used, the int for negative specifies how many "noise words" should be drown. If set to 0, no negative sampling is used. - (5, 20)
* `workers` = int - Use these many worker threads to train the model (=faster training with multicore machines)

In [36]:
# This line makes a model
# You first put in your sentences
# then you can OPTIONALLY specify a number of parameters
# vector_size is the size of the hidden layer
# window is the size of the skip-gram window
# min_count sets a minimum number of times that a word has to appear
model = Word2Vec(sentences = sentences, 
                     window=1, 
                     min_count=1)

In [37]:
model.wv['SAM']

array([-1.8335080e-03, -3.6692363e-03, -4.4667190e-03, -4.4844942e-03,
       -5.4504629e-03, -5.7248897e-03, -7.9307184e-03,  1.0403933e-02,
        6.0576736e-03, -4.2591104e-03,  2.6673831e-03, -8.1059700e-03,
        7.6808184e-03,  8.6215511e-03,  1.1056619e-03, -7.0835459e-03,
       -2.5074102e-03,  4.6011433e-03, -3.2659450e-03,  2.4875356e-03,
        9.6991397e-03,  4.3403022e-03, -4.5572654e-03,  5.4771909e-03,
       -3.0299951e-03, -6.4314143e-03,  6.6607306e-03, -9.1410596e-03,
       -1.3413969e-03, -1.3787008e-03, -8.2133701e-03, -1.3494280e-03,
        5.8000386e-03, -6.0228663e-03, -7.1120830e-03,  6.8435874e-03,
       -3.3041353e-03, -7.8698359e-03, -1.4567543e-04, -1.3410054e-04,
        7.8134621e-03,  3.9136433e-04,  7.7017015e-03, -9.5348051e-03,
        4.3336679e-03,  6.0064094e-03,  9.1328181e-04, -3.1854496e-03,
        1.1199160e-03, -6.0905213e-04, -7.8726308e-03, -7.0880516e-03,
        9.4409636e-04, -2.2165747e-03,  9.5937811e-03, -1.0977199e-03,
      

In [38]:
model.wv['EGGS']

array([ 0.00113743,  0.00686352,  0.01001572,  0.00927828, -0.00780672,
        0.0061011 , -0.00562365, -0.0002332 ,  0.00019445,  0.00595561,
        0.0046361 ,  0.00415446,  0.00959406,  0.00063888, -0.00571437,
       -0.00651644,  0.00680376, -0.00533495, -0.00309005,  0.00348334,
       -0.00215561, -0.00599159, -0.00192431,  0.00114807,  0.00208947,
        0.00608267, -0.00568869,  0.00324019,  0.00711634,  0.00217023,
        0.0055585 , -0.00504116,  0.00623016, -0.0081352 ,  0.00334511,
       -0.00883773, -0.00245555, -0.00906668, -0.00192501, -0.00546587,
       -0.00371054,  0.00101317,  0.00262924, -0.00124675, -0.00800904,
       -0.00610413,  0.00070493, -0.00421979, -0.00937551, -0.00056603,
        0.00695632,  0.00562716, -0.01009007,  0.00297711, -0.00606834,
       -0.00925559,  0.00028271, -0.00040779, -0.00693433, -0.00636747,
       -0.00250179,  0.00702521, -0.00690999,  0.00782987, -0.00074454,
        0.00153528,  0.00931027,  0.00503959, -0.0040732 ,  0.00

In [39]:
model.wv.most_similar(['HAM'])

[('FOX', 0.20511563122272491),
 ('I', 0.18071936070919037),
 ('AND', 0.1534055918455124),
 ('COULD', 0.12676802277565002),
 ('LIKE', 0.12494883686304092),
 ('tries', 0.11725952476263046),
 ('.', 0.11654206365346909),
 ('SEE', 0.10057325661182404),
 ('HOUSE', 0.09586508572101593),
 ('SAM', 0.09576644748449326)]

Since we spent so much time and energy training this model we may want to save it.

In [40]:
model.save("green_eggs_and_ham.model")

We can load it later.

In [41]:
model = Word2Vec.load("green_eggs_and_ham.model")

Now when training an actual model you'll likely want to know all the bells and whistles for tuning the model. You can find all that and more here: https://radimrehurek.com/gensim/models/word2vec.html?highlight=word2vec#module-gensim.models.word2vec

## An Improvement on Word2Vec
A nice improvement on Word2Vec was made by Facebook researchers (including Mikolov) called, fasttext, https://arxiv.org/abs/1607.04606.

The key idea to the improvement was to replace words and phrases as the base unit input layer with partial character -grams of words. For example instead of "apples" they used things like "app", "ppl", "ple", and "les".

This is also implementable with gensim. Here is the documentation, https://radimrehurek.com/gensim_3.8.3/models/fasttext.html.

Below I'll demonstrate Facebook's pretrained model trained on Wikipedia. Note don't try and run this code right now because it takes a long time to download the model. Just watch the code, and if you're interested in the model you can always play with it later.

In [42]:
ft = api.load('fasttext-wiki-news-subwords-300')

[=================================================-] 100.0% 958.2/958.4MB downloaded


In [43]:
## Let's look at the top 20 words
for i in range(20):
    print(ft.index_to_key[i])

,
the
.
and
of
to
in
a
"
:
)
that
(
is
for
on
*
with
as
it


In [44]:
## And just to note we can use this model in exactly
## the same way as Word2Vec
ft.similar_by_word("apple",topn=20)

[('apples', 0.8046640753746033),
 ('pear', 0.6897592544555664),
 ('peach', 0.6626990437507629),
 ('fruit', 0.6596963405609131),
 ('apple-', 0.6546189785003662),
 ('appley', 0.6466962099075317),
 ('pippin', 0.6454442143440247),
 ('pome', 0.6110042333602905),
 ('apple-tree', 0.6037725210189819),
 ('berry', 0.602673351764679),
 ('applesauce', 0.6012105345726013),
 ('applejack', 0.6003251075744629),
 ('starfruit', 0.5956475734710693),
 ('cherry', 0.594257116317749),
 ('strawberry', 0.5939095616340637),
 ('banana', 0.5924690961837769),
 ('pears', 0.5920964479446411),
 ('currant', 0.59149169921875),
 ('crabapple', 0.5898768305778503),
 ('watermelon', 0.5855808258056641)]

In [45]:
ft.similar_by_word("ppl",topn=20)

[('ppls', 0.7948858737945557),
 ('ppl.', 0.7874938249588013),
 ('poeple', 0.761584997177124),
 ('pplz', 0.7385753989219666),
 ('peolpe', 0.6922174096107483),
 ('people.I', 0.687359631061554),
 ('pple', 0.6842299103736877),
 ('peole', 0.6832447052001953),
 ('peopl', 0.6651833057403564),
 ('peple', 0.6493471264839172),
 ('people.', 0.6474063396453857),
 ('peope', 0.6439474821090698),
 ('americans', 0.6331156492233276),
 ('guys.', 0.624374270439148),
 ('peopel', 0.6218089461326599),
 ('evryone', 0.621412456035614),
 ('peolple', 0.6154645085334778),
 ('brits', 0.6141127347946167),
 ('guyz', 0.6072280406951904),
 ('coz', 0.5926057696342468)]

In [46]:
test = ft['king'] - ft['man'] + ft['woman']
ft.similar_by_vector(test,topn=5)

[('king', 0.8185327053070068),
 ('queen', 0.7570335865020752),
 ('queen-mother', 0.6896809339523315),
 ('king-', 0.6787333488464355),
 ('queen-consort', 0.6555202603340149)]

That's it for this notebook. I hope you enjoyed playing around with `gensim`'s word embedding models!